name              'varnish'
maintainer        'Sous Chefs'
maintainer_email  'ops@yola.com'
license           'Apache-2.0'
description       'Installs and configures varnish'
version           '5.0.23'
source_url        'https://github.com/yola/varnish'
issues_url        'https://github.com/yola/varnish/issues'
chef_version      '>= 15.5'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'redhat'
supports 'ubuntu'

depends 'yum', '>= 7.2'
depends 'yum-epel'
